language: node_js
dist: focal
services:
  - postgresql
cache:
  npm: true
  yarn: true
  directories:
    - ~/.cache/Cypress
notifications:
  email: false
addons:
  apt:
    packages:
      - libgconf-2-4
before_script:
  # ensure application config template is copied, as the server requires these env-var configs to be available
  - psql -c 'create database veritext_box;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD postgres;" -U postgres
  - yarn setup
