language: node_js
dist: focal
env:
  global:
  - PGPORT=5432
  - PGUSER=postgres
  - PGPASSWORD=postgres
  - PGHOST=localhost
services:
  - postgresql
cache:
  npm: true
  yarn: true
  directories:
    - ~/.cache/Cypress
notifications:
  email: false
addons:
  apt:
    packages:
      - libgconf-2-4
before_script:
  # ensure application config template is copied, as the server requires these env-var configs to be available
  - yarn setup
