# BE
# PORT
PORT: 8080

# DATABASE
# DATABASE_URL: mysql://root:password@localhost:3306/dev

# TOKEN
# SECRET_KEY: secretKey

# LOG
LOG_FORMAT: dev
LOG_DIR: ../logs

# CORS
ORIGIN: "*"
CREDENTIALS: true

# DATABASE
DATABASE_URL: your-database-url