development:
  # ENV
  NODE_ENV: development

  # FE
  API_URL: http://localhost:8080/api/v1

  # BE
  PORT: 8080

  # LOG
  LOG_FORMAT: dev
  LOG_DIR: ../logs

  # CORS
  ORIGIN: "*"
  CREDENTIALS: true

  # DATABASE
  DATABASE_URL: your-local-postgres-url

# production:
#   # ENV
#   ENV: production

#   # FE
#   API_URL:

#   # BE
#   PORT:

#   # LOG
#   LOG_FORMAT: dev
#   LOG_DIR: ../logs

#   # CORS
#   ORIGIN:
#   CREDENTIALS: true

#   # DATABASE
#   DATABASE_URL: your-production-postgres-url
#   SHADOW_DATABASE_URL: your-production-shadow-postgres-url